server:
  port: 8083

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: lb://student-module
        predicates:
        - Path=/api/v1/student/**
        filters:
        - AuthenticationFilter
       
       
      - id: courseModule
        uri: lb://course-module
        predicates:
        - Path=/api/v1/course/**
        filters:
        - AuthenticationFilter
        
        
      - id: authModule
        uri: lb://auth-module
        predicates:
        - Path=/api/v1/auth/**
        filters:
        - name: RequestSize
          args:
            MaxSize: 5000000
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
          
        