spring:
  application:
    name: eureka-service

server:
  port: 8085


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8085/eureka
  dashboard:
    path: /eurekawebui    