server:
  port: 8082

spring:
  application:
    name: course-module
  datasource:
    url: jdbc:mysql://localhost:3306/ms_1_course?useSSL=false
    username: root
    password: password
  
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
   
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka